### ISSUE TITLE
Unable to create a new project/Old project not recognized 

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#60]
Hello,
I downloaded the latest version of the toolbox and I cannot create new projects nor open old ones. The older project name do not appear in the saved document file. Nothing can be done. 
![image](https://user-images.githubusercontent.com/116119599/232136415-d2015f96-1aae-4015-bb62-ba691e2e2886.png)

To Reproduce :
1. Creating a new project and naming it
2. Bug 
![image](https://user-images.githubusercontent.com/116119599/232136341-12239596-fb80-4c84-a462-00568acd0e4c.png)

**Comment by BrunoOFSouza** [comment]
Hi @C-A25 

The bug was fixed in the commit 8a69878465e25126a5d2a788e6a359e895d7528b

However, note that the code in the Master branch is the newest version that is still under development.
We suggest that you upload the latest versions from the ***release_Astrocyte-v1.5*** branch. This branch is more stable and less prone to bugs. 

But thanks for pointing this out!

**Comment by C-A25** [comment]
Hello,
Oh, I didn't know. I'll go back to the latest versions from the Astrocyte-v1.5 branch to make things easier.

Thank you!

**Comment by BrunoOFSouza** [comment]
It is ok. Actually, this bug as also present in the Astrocyte branch as well, so it was a good thing to let us know! :)
